### ISSUE TITLE
Does not print partial lines

### ISSUE THREAD

**Issue by pseyfert-sevensense** [pycontribs/subprocess-tee#116]
I thought subprocess-tee would fit in nicely for the following example

```py
from subprocess_tee import run
o = run("ssh remotehost -t sudo cat /super/secret/file"))
# now trim of the password prompt from o
```

i.e. someone running my python script should see the sudo password prompt from the remote host, and I can capture the `cat` output in a local variable (i don't want my users to blindly type their sudo passwords, assuming the ssh connection got established, though they still have to trust me that i'm not doing anything nasty with the password). yet, this doesn't work as desired because there is no linefeed after `[sudo] password for <user>:` and the prompt only becomes printed by subprocess-tee after the user hits return.

**Comment by ssbarnea** [comment]
That is to be expected and there are no plans to fix it. Still, I would not mind reviewing a PR.
