### ISSUE TITLE
check=True isn't supported by run()

### ISSUE THREAD

**Issue by sprt** [pycontribs/subprocess-tee#26]
Currently, this can't be used as a drop-in replacement for `subprocess.run()` as passing `check=True` isn't supported directly. A simple fix would be to call `check_returncode()` manually on the returned `CompletedProcess`.

BTW, IMO `subprocess_tee.run()` should raise an error when it's passed unsupported arguments. This would avoid silent unexpected behavior.

**Comment by ssbarnea** [comment]
Correct, patch would be welcomed. I am happy to make a release after.
