### ISSUE TITLE
py38: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait()

### ISSUE THREAD

**Issue by ssbarnea** [pycontribs/subprocess-tee#3]
Current implementation is producing a deprecation warning in py39:
```
subprocess_tee/__init__.py:46: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
    await asyncio.wait(
```

https://github.com/pycontribs/subprocess-tee/blob/main/lib/subprocess_tee/__init__.py#L46

If anyone knows how to address this deprecation warning without breaking backwards compatibility with py36+, I would greatly appreciate.

**Comment by absconder74** [comment]
Hello, how did you solve this problem?

**Comment by ssbarnea** [comment]
@absconder74 Look at https://github.com/pycontribs/subprocess-tee/pull/5/files#diff-63c7ad3d96f7c28b4131110ec48fb61fbd793d90de91c63c1c633bbf729a3095R44-R61 section.
