### ISSUE TITLE
not working on windows

### ISSUE THREAD

**Issue by srl295** [pycontribs/subprocess-tee#53]
maybe related to #15 

On windows I'm trying to sublaunch a batch script (Which happens to be `conda.bat`). The equivalent works on unix/mac.

I had some success with:  `subprocess_tee.run(['…path to conda.bat', …], executable="c:/windows/system32/cmd.exe", …)` but perhaps there's a better way.

the error I got is that windows cannot find the file specified.

**Comment by ssbarnea** [comment]
Duplicate of #59
