### ISSUE TITLE
Looking for co-maintainers

### ISSUE THREAD

**Issue by ssbarnea** [pycontribs/subprocess-tee#8]
While this is a very small library that does not need much maintenance I am interested in having a couple of co-maintainers, so in case one of us becomes unavailable, users would not end-up having to fork it to patch it.

**Comment by decentral1se** [comment]
I am watching the repo, can't promise anything but just letting you know. Think I already have pycontribs permissions.

**Comment by ssbarnea** [comment]
Closing but if anyone is interested to join, post a message.
