### ISSUE TITLE
Platform requirements not clearly advertised

### ISSUE THREAD

**Issue by jaraco** [pycontribs/subprocess-tee#84]
I started using this project intending to use it to wrap tox to detect known failed builds, and I didn't realize that it only runs on some systems. Best I can tell, the non-Windows support is only declared in closed issues. Perhaps the project could expose the supported platforms is Trove classifiers so they appear prominently on the PyPI page.

**Comment by ssbarnea** [comment]
@jaraco Usage on Windows was outside my scope but I would not refuse a PR that adds support for Windows as I do realise that this might be wanted by others.

**Comment by ssbarnea** [comment]
Fixed! I also mention that I will will not oppose any PR that adds support for Windows.
